version: '3'

services:
  node-app:
    build: .
    image: mlmh-prod
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/api-mlmh
    ports:
      - '3001:3001'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/api-mlmh
    networks:
      - node-network

  mongodb:
    image: mongo:4.4.6
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
